### ISSUE TITLE
configure failure

### ISSUE THREAD

**Issue by loveshack** [RBigData/pbdSLAP#19]
I had to patch inst/test_intface/00_make.sh like this to make it work with gfortran and the EPEL6-packaged R 3.1.3.  It reports FLIBS as -lgfortran -lm, not -lgfortranbegin -lgfortran -lm as it would need to be with a Fortran main.  The usual advice is to link mixed source with the Fortran compiler anyhow.

```
--- pbdSLAP/pbdSLAP/inst/test_intface/00_make.sh~	2014-12-24 03:14:53.000000000 +0000
+++ pbdSLAP/pbdSLAP/inst/test_intface/00_make.sh	2015-04-08 13:55:47.502113822 +0100
@@ -5,8 +5,7 @@
 FLIBS=`${R_HOME}/bin/R CMD config FLIBS`
 
 ${CC} -c *.c
-${FC} -c *.f
-${CC} -o xintface *.o ${FLIBS}
+${FC} -o xintface *.o *.f
 
 ./xintface
 rm -f *.o xintface > /dev/null
```

**Comment by snoweye** [comment]
Great, but CRAN may not like this change. For personal usage, replace Makevars with -DAdd_ may good enough.
